### ISSUE TITLE
Case #2 - Design Pattern Case

### ISSUE THREAD

**Issue by LuisDiegoMora98** [LuisDiegoMora98/TEC_CR_Algorith_Analysis_Cases#6]
Analyze and plan the strategy logic to use Observer pattern design to solve the problem.
Create implementation on C++.

We are going to develop the "a" exercise.

UML here: https://lucid.app/lucidchart/invitations/accept/664ceefc-9cfd-4bc8-9f66-b70ebf69bb0c

**Comment by LuisDiegoMora98** [comment]
@pameladinarte look:

@ljrivel will develop Strategy pattern and inherate classes.
@LuisDiegoMora98 Will develop Observer pattern with Application class.

**Comment by ljrivel** [comment]
@LuisDiegoMora98 Look at my worth in my branch, and check the questions y whatsapp
